package org.DenWorker.Java_Core._3_Exceptions._3_2_Exception_Handling_Try_Catch;

public class Task_3_2_2 {
    public static void main(String[] args) {
        System.out.println("catch (RuntimeException e)");
        System.out.println("finally");
    }
}
